version: '3'
services:
  app:
    image: toancong/phpup:2
    depends_on:
      - db
      - queue
    ports:
      - 11400:80
    volumes:
      - .:/var/www/app
      - ./storage/tools/app_queue.conf:/etc/supervisor/conf.d/app_queue.conf
      # this mount will disable xdebug which enabled for dev in default
      # - ./storage/tools/empty:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /var/www/app
    environment:
      PHP_MEM_LIMIT: -1

  appdoc:
    image: phpdoc/phpdoc
    volumes:
      - .:/data

  db:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_vue
      MYSQL_USER: abc123
      MYSQL_PASSWORD: root
    ports:
      - 14307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 11409:80
    depends_on:
      - db
    environment:
      PMA_HOSTS: db
      PMA_USER: root
      PMA_PASSWORD: root

  queue:
    image: schickling/beanstalkd
